name = "entity-viewer-prod"
compatibility_date = "2024-03-02"

[build]
command = "chmod +x build.sh && ./build.sh"

[build.upload]
format = "directory"

[site]
bucket = ".output"

[pages]
pages_build_output_dir = ".output"
